apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-auditoria-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-catastro
  template:
    metadata:
      labels:
        app: app-catastro
    spec:
      containers:
      - name: app-catastro
        image: gcr.io/apps-no-monoliticas-415223/servicio_auditoria
        env:
          - name: PULSAR_TOKEN
            valueFrom:
              secretKeyRef:
                name: mi-secreto
                key: PULSAR_TOKEN
