version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: catastro.Dockerfile
    command: gunicorn -b :8000 servicio_catastro:app
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
  web2:
    build:
      context: .
      dockerfile: propiedades.Dockerfile
    command: gunicorn -b :8001 servicio_propiedades:app
    volumes:
      - .:/usr/src/app
    ports:
      - "8001:8001"
    environment:
      - FLASK_ENV=development